# numpyex

##### Numpy
##### Numerical Python
##### 고성능 수치 계산을 위한 라이브러리
##### 벡터나 행렬 연산에 편리한 기능 제공
##### 모든 원소는 같은 자료형만 가능

In [9]:
import numpy as np
a = np.arange(15)
print(a)
a = a.reshape(3, 5, order ='F')  # C 행부터 할당 F 열부터 할당
print(a)
print(type(a))
print(a.shape)
print(a.dtype)
print(a.ndim)
print(a.size)
# print (dir(np))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  3  6  9 12]
 [ 1  4  7 10 13]
 [ 2  5  8 11 14]]
<class 'numpy.ndarray'>
(3, 5)
int32
2
15


In [51]:
b = np.array([-1, 2, 5, -3, 0, 7, -9, 7, -4, -7]) # List
print(type(b))

t = (10, 20, 30, 40, 50)         # Tuple
print(type(t))
t = np.array(t)
print(type(t))

s = {10, 20, 30, 40, 50}         # Set
print(type(s))
s = np.array(s)                
print(type(s))

print(b.shape)
print(b.ndim)
print(b.dtype)
print(b)

# print(help(np.arange))

print(np.abs(b))                # 절대값
print(np.sqrt(np.abs(b)))       # 제곱근
print(np.square(b))             # 제곱
print(np.isnan(b))              # NaN 여부
print(np.sum(b))                # 합계
print(np.mean(b))               # 평균
print(np.max(b))                # 최대값
print(np.min(b))                # 최소값
print( np.argmax(b))            # 최대값 인덱스
print( np.argmin(b))            # 최소값 인덱스
print(np.sort(b))               # 정렬 오름차순
print(np.sort(b)[::-1])         # 정렬 내림차순  [start:end:step]

<class 'numpy.ndarray'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'set'>
<class 'numpy.ndarray'>
(10,)
1
int32
[-1  2  5 -3  0  7 -9  7 -4 -7]
[1 2 5 3 0 7 9 7 4 7]
[1.         1.41421356 2.23606798 1.73205081 0.         2.64575131
 3.         2.64575131 2.         2.64575131]
[ 1  4 25  9  0 49 81 49 16 49]
[False False False False False False False False False False]
-3
-0.3
7
-9
5
6
[-9 -7 -4 -3 -1  0  2  5  7  7]
[ 7  7  5  2  0 -1 -3 -4 -7 -9]
